In [1]:
import numpy as np

In [2]:
revenue = np.array([[180, 200, 220], [24,36,40], [12,18,20]])
expenses = np.array([[80,90,100], [10,16,20], [8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
price_per_unit * units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [6]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [7]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenues_inr = 75*revenues_usd
revenues_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [8]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [9]:
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount

array([1900, 2640, 1430])

In [21]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [22]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [23]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [24]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [25]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [26]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [27]:
mae_np(y_predicted, y_true)

0.5

In [28]:
np.log([0])

C:\Users\Najmi\AppData\Local\Temp\ipykernel_2852\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])